//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace R6SAdapter.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("R6SAdapter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 By Coldthunder11 的本地化字符串。
        /// </summary>
        public static string AboutLinkLabelText {
            get {
                return ResourceManager.GetString("AboutLinkLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup successfully! 的本地化字符串。
        /// </summary>
        public static string BackupSuccessfully {
            get {
                return ResourceManager.GetString("BackupSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BuildSteamLibrary 的本地化字符串。
        /// </summary>
        public static string BuildSteamLibraryButtonText {
            get {
                return ResourceManager.GetString("BuildSteamLibraryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Version: Steam 的本地化字符串。
        /// </summary>
        public static string CurrentVersionSteam {
            get {
                return ResourceManager.GetString("CurrentVersionSteam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Version: Uplay 的本地化字符串。
        /// </summary>
        public static string CurrentVersionUplay {
            get {
                return ResourceManager.GetString("CurrentVersionUplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exsist 的本地化字符串。
        /// </summary>
        public static string Exsist {
            get {
                return ResourceManager.GetString("Exsist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to find R6S. 的本地化字符串。
        /// </summary>
        public static string FailedtoFindR6S {
            get {
                return ResourceManager.GetString("FailedtoFindR6S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click here to learn how to use this program. 的本地化字符串。
        /// </summary>
        public static string FirstUseHelpLinkLabelText {
            get {
                return ResourceManager.GetString("FirstUseHelpLinkLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 R6SDirectory 的本地化字符串。
        /// </summary>
        public static string InstallDirectoryLabelText {
            get {
                return ResourceManager.GetString("InstallDirectoryLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NoExsist 的本地化字符串。
        /// </summary>
        public static string NoExsist {
            get {
                return ResourceManager.GetString("NoExsist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please backup files first. 的本地化字符串。
        /// </summary>
        public static string PleaseBackupFilesFirst {
            get {
                return ResourceManager.GetString("PleaseBackupFilesFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PleaseSelectR6SInstallDirectory 的本地化字符串。
        /// </summary>
        public static string PleaseSelectR6SInstallDirectory {
            get {
                return ResourceManager.GetString("PleaseSelectR6SInstallDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RunSteamVersion 的本地化字符串。
        /// </summary>
        public static string RunSteamVersionButtonText {
            get {
                return ResourceManager.GetString("RunSteamVersionButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RunUplayVersion 的本地化字符串。
        /// </summary>
        public static string RunUplayVersionButtonText {
            get {
                return ResourceManager.GetString("RunUplayVersionButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BackupSteamFiles 的本地化字符串。
        /// </summary>
        public static string SaveSteamFilesButtonText {
            get {
                return ResourceManager.GetString("SaveSteamFilesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BackupUplayFiles 的本地化字符串。
        /// </summary>
        public static string SaveUplayFilesButtonText {
            get {
                return ResourceManager.GetString("SaveUplayFilesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SelectR6SDirectory 的本地化字符串。
        /// </summary>
        public static string SelectInstallDirectoryButtonText {
            get {
                return ResourceManager.GetString("SelectInstallDirectoryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SteamBackup: 的本地化字符串。
        /// </summary>
        public static string SteamBackup {
            get {
                return ResourceManager.GetString("SteamBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch success. 的本地化字符串。
        /// </summary>
        public static string SwitchSuccess {
            get {
                return ResourceManager.GetString("SwitchSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SwitchVersion 的本地化字符串。
        /// </summary>
        public static string SwitchVersionButtonText {
            get {
                return ResourceManager.GetString("SwitchVersionButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UplayBackup: 的本地化字符串。
        /// </summary>
        public static string UplayBackup {
            get {
                return ResourceManager.GetString("UplayBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Github to feedback 的本地化字符串。
        /// </summary>
        public static string ViewGithub {
            get {
                return ResourceManager.GetString("ViewGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 R6SAdapter 的本地化字符串。
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
